version: '3.7'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_HOST_IP: 172.17.0.1

  TELEGRAM_INPUT_FILE_QUEUE: TELEGRAM_INPUT_FILE
  TELEGRAM_INPUT_TEXT_QUEUE: TELEGRAM_INPUT_TEXT
  TELEGRAM_OUTPUT_TEXT_QUEUE: TELEGRAM_OUTPUT_TEXT
  EXECUTE_MINIDLNA_COMMAND_QUEUE: EXECUTE_MINIDLNA_COMMAND
  EXECUTE_TORRENT_COMMAND_QUEUE: EXECUTE_TORRENT_COMMAND

  BOT_TOKEN: 1859184957:AAG24FRjQND5gSaiblsaQgZe_nLNId8sOx8
  BOT_NAME: koTorrentBot

  LONG_PAUSE_MILIS: 10000
  MEDIUM_PAUSE_MILIS: 5000
  SMALL_PAUSE_MILIS: 500

  DIR_TORRENT_COMPLETE: /home/media/torrent/complete/
  DIR_TORRENT_INCOMPLETE: /home/media/torrent/downloads/
  DIR_TORRENT_WATCH: /home/media/torrent/torrent_files/
  DIR_MEDIA_SHOW: /home/media/

  PING: /ping
  PONG: pong
services:
  jars_builder:
    build:
      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/kot-builder/builder/Dockerfile
    environment: *common-variables
    container_name: "jars_builder"
    volumes:
      - ./runner/jars:/home/gradle/jars