version: '3.4'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_HOST_IP: 172.17.0.1
  TELEGRAM_INPUT_FILE_QUEUE: TELEGRAM_INPUT_FILE
  TELEGRAM_INPUT_TEXT_QUEUE: TELEGRAM_INPUT_TEXT
  TELEGRAM_OUTPUT_TEXT_QUEUE: TELEGRAM_INPUT_TEXT
  BOT_TOKEN: 1859184957:AAF2DaTJpaOEj2I6T2Vf35fOJszp9skPeiE
  BOT_NAME: koTorrentBot
services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    hostname: rabbitmq
    restart: always
    environment: *common-variables
    ports:
      - 5672:5672
      - 15672:15672
  bot:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-microBot
    environment: *common-variables
    restart: always
    container_name: "bot"
    depends_on:
      - rabbitmq
  #    volumes:
  #      - libsdata:/home/app/
  text_handler:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-text
    environment: *common-variables
    restart: always
    container_name: "text_handler"
    depends_on:
      - rabbitmq
  #    volumes:
  #      - libsdata:/home/app/
  file_handler:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-file
    environment: *common-variables
    restart: always
    container_name: "file_handler"
    depends_on:
      - rabbitmq
    volumes:
      - mediadata:/home/media/
  torrent:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-torrent
    environment: *common-variables
    restart: always
    container_name: "torrent"
    depends_on:
      - rabbitmq
    volumes:
      - mediadata:/home/media/
    ports:
      - 9091:9091
      - 51413:51413
volumes:
  #  libsdata:
  #    driver: local
  #    driver_opts:
  #      o: bind
  #      type: none
  #      device: ./jars
  mediadata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mediadata