services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pswrd
    ports:
      - 5672:5672
      - 15672:15672
  jar_builder:
    build:
      context: .
#      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-jar_builder
    depends_on:
      - rabbitmq
    volumes:
      - libsdata:/app
  bot:
    build:
      context: .
#      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-microBot
    restart: always
    depends_on:
      - jar_builder
volumes:
  libsdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./jars