services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pswrd
    ports:
      - 5672:5672
      - 15672:15672
#  downloader:
#    build:
#      context: .
#      #      context: https://github.com/halushko/kino-cat.git
#      dockerfile: ./config/dockerfiles/Dockerfile-downloader
#    depends_on:
#      - rabbitmq
#    container_name: "downloader"
#    volumes:
#      - libsdata:/home/gradle/
  bot:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-microBot
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pswrd
      RABBIT_PORT: 5672
      RABBIT_HOST_IP: 172.17.0.1
    restart: always
    container_name: "bot"
    depends_on:
      - rabbitmq
    volumes:
      - libsdata:/home/app/
volumes:
  libsdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./jars