version: '3.8'

x-common-variables: &common-variables
  RABBITMQ_DEFAULT_USER: rabbit_user
  RABBITMQ_DEFAULT_PASS: rabbit_pswrd
  RABBIT_PORT: 5672
  RABBIT_HOST_IP: 172.17.0.1
  TELEGRAM_INPUT_FILE_QUEUE: TELEGRAM_INPUT_FILE
  TELEGRAM_INPUT_TEXT_QUEUE: TELEGRAM_INPUT_TEXT
  TELEGRAM_OUTPUT_TEXT_QUEUE: TELEGRAM_OUTPUT_TEXT
  EXECUTE_TORRENT_COMMAND_QUEUE: EXECUTE_TORRENT_COMMAND
  BOT_TOKEN: 1859184957:AAG24FRjQND5gSaiblsaQgZe_nLNId8sOx8
  BOT_NAME: koTorrentBot
  LONG_PAUSE_MILIS: 10000
  MEDIUM_PAUSE_MILIS: 5000
  SMALL_PAUSE_MILIS: 500
  PING: /ping
  PONG: pong
services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    hostname: rabbitmq
    restart: always
    environment: *common-variables
    ports:
      - 5672:5672
      - 15672:15672
  bot:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-microBot
    environment: *common-variables
    restart: always
    container_name: "bot"
    depends_on:
      - rabbitmq
  text_handler:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-text
    environment: *common-variables
    restart: always
    container_name: "text_handler"
    depends_on:
      - rabbitmq
  file_handler:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-file
    environment: *common-variables
    restart: always
    container_name: "file_handler"
    depends_on:
      - rabbitmq
    volumes:
      - ./mediadata/torrent/torrent_files:/home/torrent_files/
  torrent:
    build:
      context: .
      #      context: https://github.com/halushko/kino-cat.git
      dockerfile: ./config/dockerfiles/Dockerfile-torrent
    environment: *common-variables
    restart: always
    container_name: "torrent"
    depends_on:
      - rabbitmq
    volumes:
      - ./mediadata:/home/media/
      - ./torrentdata/torrents:/var/lib/transmission/config/torrents
      - ./torrentdata/resume:/var/lib/transmission/config/resume
    ports:
      - 9091:9091
      - 51413:51413